project_id = "fdbcuegidxvdanpoqztv"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_anonymous_users = false
enable_email_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[edge_functions]
enabled = true
port = 54323

[functions.cognito-webhook]
verify_jwt = false

[functions.fireblocks-get-vaults]
verify_jwt = true

[functions.fireblocks-get-assets]
verify_jwt = true

[functions.fireblocks-create-vault]
verify_jwt = true

[functions.fireblocks-initiate-transfer]
verify_jwt = true

[functions.mint-tokens]
verify_jwt = true

[functions.get-token-balance]
verify_jwt = true

[functions.get-pledges]
verify_jwt = true

[functions.liquidity-get-pools]
verify_jwt = true

[functions.liquidity-create-pool]
verify_jwt = true

[functions.liquidity-add-remove]
verify_jwt = true

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"